### ISSUE TITLE
Weekly review template example

### ISSUE THREAD

**Issue by Ingvar33** [jethrokuan/.emacs.d#3]
Many thanks for a great example!
I'm newbie in Emacs and I have a question. Could you give an example of template file
~/.org/gtd/templates/weekly_review.org ?

**Comment by jethrokuan** [comment]
Hi there, my weekly review file is here: 

https://gist.github.com/jethrokuan/62aa6c9f1e5b31a7f5f0a742a55df8a9

let me know if you have any other questions.
